# -*- coding: utf-8 -*-
"""graficas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKvHAeCNUJmsFLzrBek_vYq_Rgawtyvd
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Configurar estilo general
sns.set(style="whitegrid", palette="muted")

# Cargar el dataset
df = pd.read_csv("vgsales.csv")

# 1 Ventas por año
ventas_por_año = df.dropna(subset=['Year']).groupby('Year')['Global_Sales'].sum().reset_index()
ventas_por_año['Year'] = ventas_por_año['Year'].astype(int)


# 2 Ventas por género
ventas_por_genero = df.groupby('Genre')['Global_Sales'].sum().reset_index().sort_values('Global_Sales', ascending=False)


# 3 Ventas por plataforma
ventas_por_plataforma = df.groupby('Platform')['Global_Sales'].sum().reset_index().sort_values('Global_Sales', ascending=False)


# Crear figura de 3 subgráficas
fig, axes = plt.subplots(3, 1, figsize=(12, 16))
fig.suptitle(' Análisis de Ventas Globales de Videojuegos', fontsize=18, fontweight='bold')

#Gráfica 1: Ventas por año
sns.lineplot(data=ventas_por_año, x='Year', y='Global_Sales', marker='o', ax=axes[0], color='royalblue')
axes[0].set_title(' Ventas Globales por Año', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Año')
axes[0].set_ylabel('Ventas Globales (millones)')
axes[0].grid(True, linestyle='--', alpha=0.4)

#Gráfica 2: Ventas por género
sns.barplot(data=ventas_por_genero, x='Genre', y='Global_Sales', palette='viridis', ax=axes[1])
axes[1].set_title(' Ventas Globales por Género', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Género')
axes[1].set_ylabel('Ventas Globales (millones)')
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=45)

#Gráfica 3: Ventas por plataforma
sns.barplot(data=ventas_por_plataforma, x='Platform', y='Global_Sales', palette='coolwarm', ax=axes[2])
axes[2].set_title(' Ventas Globales por Plataforma', fontsize=14, fontweight='bold')
axes[2].set_xlabel('Plataforma')
axes[2].set_ylabel('Ventas Globales (millones)')
axes[2].set_xticklabels(axes[2].get_xticklabels(), rotation=45)

#Ajustar espacios y mostrar
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.show()